language: objective-c
osx_image: xcode9
script:
        - xcodebuild clean build -project SpotifyKit.xcodeproj -scheme SpotifyKitMac CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
        - xcodebuild clean test -project SpotifyKit.xcodeproj -scheme SpotifyKitiOS -destination "platform=iOS Simulator,name=iPhone 8,OS=12.0" CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
